/* eslint-disable */
// Generated by Wrangler by running `wrangler types test/e2e/outbound-git-rewrite-dind-probe.worker-configuration.d.ts --config wrangler.outbound-git-rewrite-dind-probe.jsonc --env-file /dev/null --include-runtime=false` (hash: 1d7d6e5cb4dd091b444efbce3f566653)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./outbound-git-rewrite-dind-probe.worker');
    durableNamespaces: 'OutboundGitRewriteDindProbeSandbox';
  }
  interface Env {
    PROBE_SANDBOX: DurableObjectNamespace<
      import('./outbound-git-rewrite-dind-probe.worker').OutboundGitRewriteDindProbeSandbox
    >;
  }
}
interface Env extends Cloudflare.Env {}
