/* eslint-disable */
// Generated by Wrangler by running `wrangler types test/e2e/outbound-git-rewrite-probe.worker-configuration.d.ts --config wrangler.outbound-git-rewrite-probe.jsonc --env-file /dev/null --include-runtime=false` (hash: 40c21212a45d20b34254f7087834b3e0)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./outbound-git-rewrite-probe.worker');
    durableNamespaces: 'OutboundGitRewriteProbeSandbox';
  }
  interface Env {
    PROBE_SANDBOX: DurableObjectNamespace<
      import('./outbound-git-rewrite-probe.worker').OutboundGitRewriteProbeSandbox
    >;
  }
}
interface Env extends Cloudflare.Env {}
