/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b35132c324f0762f0633ac711ebb3ef1)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		AUTO_ROUTING_CONFIG: KVNamespace;
		AUTO_ROUTING_CLASSIFIER_METRICS: AnalyticsEngineDataset;
		INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		O11Y_CF_AE_API_TOKEN: SecretsStoreSecret;
		O11Y_CF_ACCOUNT_ID: "e115e769bcdd4c3d66af59d3332cb394";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "O11Y_CF_ACCOUNT_ID">> {}
}
