function escapeForDoubleQuotedShell(value: string): string {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('$', '\\$')
    .replaceAll('`', '\\`');
}

export function buildFixReviewPrompt(prUrl: string): string {
  const checkoutUrl = escapeForDoubleQuotedShell(prUrl);

  return [
    'Process this GitHub PR review-fix workflow. Do not require input.',
    '',
    '## Target',
    '',
    `GitHub PR URL: ${prUrl}`,
    '',
    '## Steps',
    '',
    '1. Check out the target PR before reading or editing files:',
    '',
    '   ```',
    `   gh pr checkout "${checkoutUrl}"`,
    '   ```',
    '',
    '2. Determine the target PR number, URL, owner, and repo:',
    '',
    '   ```',
    "   gh pr view --json number,url --jq '{number: .number, url: .url}'",
    "   gh repo view --json owner,name --jq '{owner: .owner.login, repo: .name}'",
    '   ```',
    '',
    '3. Fetch all review comments using pagination:',
    '',
    '   ```',
    '   gh api repos/{owner}/{repo}/pulls/{number}/comments --paginate',
    '   ```',
    '',
    '4. Fetch PR details to know who the author is, and fetch the authenticated GitHub user:',
    '',
    '   ```',
    "   gh api repos/{owner}/{repo}/pulls/{number} --jq '.user.login'",
    "   gh api user --jq '.login'",
    '   ```',
    '',
    '5. Filter qualifying review comments:',
    '',
    '   - Comments not written by the PR author qualify when they are either not resolved (`resolved` is not true in the review thread) or missing a reply from the PR author (check `in_reply_to_id` chains).',
    '   - Comments written by the PR author qualify only when the authenticated GitHub user is that PR author and the review thread is still not resolved (`resolved` is not true).',
    '   - Skip PR-author comments in every other case.',
    '',
    '6. For each qualifying review comment:',
    '',
    '   a. Read the referenced file and lines to understand the context.',
    '',
    '   b. Decide if the review feedback is valid (the reviewer has a point and a code change is warranted) or not valid (the code is already correct, or the suggestion is wrong or a matter of taste with no clear improvement).',
    '',
    '   c. If valid:',
    '   - Apply only the relevant fix to the code.',
    '   - Create one commit per fixed review comment.',
    '   - Reply to the review comment using `gh api` with a very short message referencing the fix commit. Example: `Fixed in abc1234.` or `Done in abc1234.`',
    '   - React with thumbs up on the review comment:',
    '     ```',
    "     gh api repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions -f content='+1'",
    '     ```',
    '',
    '   d. If not valid:',
    '   - Reply to the review comment with a very short, polite explanation of why no change is needed. Keep it to 1-2 sentences with simple words. No jargon, no essays.',
    '   - Do not react with thumbs down on the review comment.',
    '',
    '7. After processing all comments, push all commits at once:',
    '',
    '   ```',
    '   git push',
    '   ```',
    '',
    '8. Print a short summary table: comment, status (fixed / declined), commit or reason.',
    '',
    '## Rules',
    '',
    '- Commit messages: use conventional commit format with scope, e.g. `fix(review): remove unused var`, `refactor(auth): simplify check`, `feat(cloud-agent): add timeout`. Pick the right type (`fix`, `refactor`, `feat`, `style`, `docs`, `test`, `chore`) and a short scope matching the area of code changed. Keep the subject line under 50 characters total, lowercase, no period.',
    '- Replies: max 2 sentences, plain english a 10 year old would understand.',
    '- Do NOT batch unrelated fixes into one commit. One commit per review comment.',
    '- Do NOT modify code that the review comment is not about.',
    '- If you are unsure whether feedback is valid, treat it as valid and fix it.',
    '- Use `gh api` for all GitHub interactions (replies, reactions). Do NOT use `gh pr review`.',
    '- To reply to a review comment, POST to `repos/{owner}/{repo}/pulls/{number}/comments` with `in_reply_to` set to the original comment id and `body` set to your reply text.',
  ].join('\n');
}
